services:
  postgres_db:
    image: postgis/postgis:17-3.4
    container_name: postgres_db
    environment:
      POSTGRES_USER: diego
      POSTGRES_PASSWORD: xpKk5sbJVUyWB6eLACh
      POSTGRES_DB: finance_management
    ports:
      - "25432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U diego -d finance_management" ]
      interval: 10s
      retries: 5
  finance-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3055:3055" # Porta do servidor NestJS
    volumes:
      - .:/usr/src/app # Monta o código local no contêiner
      #- /usr/src/app/node_modules # Protege o diretório node_modules do contêiner
    depends_on:
      postgres_db:
        condition: service_healthy
    entrypoint: [ "/bin/sh", "-c", "npm run postgres:migrate:dev && npm run start:dev" ]